<h2>Agregar tipo cliente</h2>

<div class="container">
	<div >
		<form action="<?php echo APP_URL.'tiposclientes/agregar'; ?>" method="POST">
			<label for="nombre">Nombre</label>
			<div class="input-group">			
				<input type="text" name="nombre" class="form-control">
				<div class="input-group-append">
					<button class="btn btn-sm btn-success" action="submit">Agregar</button>
				</div>
			</div>
		</form>
	</div>
</div>